### ISSUE TITLE
Create first version of Session Tree Component 

### ISSUE THREAD

**Issue by mx-e** [FUB-HCC/Innovonto-Core#1]
- [x] user should be able to see the hierarchical structure of inspirations and ideas of a session visualized as a tree (see image grey box only)

- [x] on hover a popover should display an entities content to the user

- [x] if the user clicks an entity the popover will stay open, even if un-hovered until user clicks elsewhere 
- [x] no styling nor responsiveness required for now   

<img width="966" alt="Screenshot 2020-02-21 at 22 26 40" src="https://user-images.githubusercontent.com/13707737/75073275-65d0e400-54f9-11ea-915f-7476d5380a68.png">

**Comment by mx-e** [comment]
@mackeprm INPUT NEEDED: dummy request json with similarity measure

**Comment by mackeprm** [comment]
{
	"children": [{
			"content": "This can enable me to interact and see where others are in my home.",
			"ideaId": "https://innovonto-core.imp.fu-berlin.de/entities/ideas/cf65b021-620f-43fe-9473-1712be788cde",
			"name": "0",
			"numberInSession": 0,
			"similarityValue": 0
		},
		{
			"children": [{
					"children": [{
						"content": "I would see when someone is moving in my home.",
						"ideaId": "https://innovonto-core.imp.fu-berlin.de/entities/ideas/726540a9-0775-48bb-bf8c-a9a7e196a5bd",
						"name": "10",
						"numberInSession": 10
					}],
					"content": "I will see where an intruder is in my home at night.",
					"ideaId": "https://innovonto-core.imp.fu-berlin.de/entities/ideas/779c37ed-e6c4-44ca-bcbf-6b4d807627ef",
					"name": "6",
					"numberInSession": 6,
					"similarityValue": 0
				},
				{
					"content": "I will know which family member is entering the home.",
					"ideaId": "https://innovonto-core.imp.fu-berlin.de/entities/ideas/8c768672-f341-47e4-9e5e-696bca0049b3",
					"name": "7",
					"numberInSession": 7,
					"similarityValue": 0
				}
			],
			"content": "I will know where my pet is in the home.",
			"ideaId": "https://innovonto-core.imp.fu-berlin.de/entities/ideas/efd50c16-af7e-48fa-825b-ff512e54817b",
			"name": "1",
			"numberInSession": 1,
			"similarityValue": 0
		},
		{
			"children": [{
				"content": "I will know if a stranger is in my home.",
				"ideaId": "https://innovonto-core.imp.fu-berlin.de/entities/ideas/c82bf1d4-dbca-4524-a722-c425ad959aa7",
				"name": "9",
				"numberInSession": 9,
				"similarityValue": 0
			}],
			"content": "I will know if someone enters my home.",
			"ideaId": "https://innovonto-core.imp.fu-berlin.de/entities/ideas/c22eddef-a9f2-4e0d-8bc7-766ce2912120",
			"name": "2",
			"numberInSession": 2,
			"similarityValue": 0
		},
		{
			"content": "I can have lights automatically turn on when I enter a room.",
			"ideaId": "https://innovonto-core.imp.fu-berlin.de/entities/ideas/9198ac8e-ef74-46e3-80fa-e2528da9910b",
			"name": "3",
			"numberInSession": 3,
			"similarityValue": 0
		},
		{
			"content": "My front door will automatically lock when I leave.",
			"ideaId": "https://innovonto-core.imp.fu-berlin.de/entities/ideas/69730105-93eb-4cad-87cf-cdd895202617",
			"name": "4",
			"numberInSession": 4,
			"similarityValue": 0
		},
		{
			"content": "I can see where people are in my home when I am not there.",
			"ideaId": "https://innovonto-core.imp.fu-berlin.de/entities/ideas/0cb9b87d-aced-4e73-8e9c-e70058dbadd6",
			"name": "5",
			"numberInSession": 5,
			"similarityValue": 0
		},
		{
			"content": "I can see if anyone is walking through the house at night.",
			"ideaId": "https://innovonto-core.imp.fu-berlin.de/entities/ideas/9f1b2d59-e393-4b46-9812-7d12360b55e0",
			"name": "8",
			"numberInSession": 8,
			"similarityValue": 0
		}
	],
	"content": "ROOT",
	"name": "root",
	"similarityValue": 0
}

**Comment by mackeprm** [comment]
The inspirations are tricky. Therefore we leave them out for now.

**Comment by mackeprm** [comment]
I will upload more example data shortly

**Comment by mackeprm** [comment]
{
  "children": [
    {
      "content": "This can enable me to interact and see where others are in my home.",
      "ideaId": "https://innovonto-core.imp.fu-berlin.de/entities/ideas/cf65b021-620f-43fe-9473-1712be788cde",
      "name": "0",
      "numberInSession": 0,
      "similarityValue": 0
    },
    {
      "children": [
        {
          "children": [
            {
              "content": "I would see when someone is moving in my home.",
              "ideaId": "https://innovonto-core.imp.fu-berlin.de/entities/ideas/726540a9-0775-48bb-bf8c-a9a7e196a5bd",
              "name": "10",
              "numberInSession": 10
            }
          ],
          "content": "I will see where an intruder is in my home at night.",
          "ideaId": "https://innovonto-core.imp.fu-berlin.de/entities/ideas/779c37ed-e6c4-44ca-bcbf-6b4d807627ef",
          "name": "6",
          "numberInSession": 6,
          "similarityValue": 0
        },
        {
          "content": "I will know which family member is entering the home.",
          "ideaId": "https://innovonto-core.imp.fu-berlin.de/entities/ideas/8c768672-f341-47e4-9e5e-696bca0049b3",
          "name": "7",
          "numberInSession": 7,
          "similarityValue": 0
        }
      ],
      "content": "I will know where my pet is in the home.",
      "ideaId": "https://innovonto-core.imp.fu-berlin.de/entities/ideas/efd50c16-af7e-48fa-825b-ff512e54817b",
      "name": "1",
      "numberInSession": 1,
      "similarityValue": 0
    },
    {
      "children": [
        {
          "content": "I will know if a stranger is in my home.",
          "ideaId": "https://innovonto-core.imp.fu-berlin.de/entities/ideas/c82bf1d4-dbca-4524-a722-c425ad959aa7",
          "name": "9",
          "numberInSession": 9,
          "similarityValue": 0
        }
      ],
      "content": "I will know if someone enters my home.",
      "ideaId": "https://innovonto-core.imp.fu-berlin.de/entities/ideas/c22eddef-a9f2-4e0d-8bc7-766ce2912120",
      "name": "2",
      "numberInSession": 2,
      "similarityValue": 0
    },
    {
      "content": "I can have lights automatically turn on when I enter a room.",
      "ideaId": "https://innovonto-core.imp.fu-berlin.de/entities/ideas/9198ac8e-ef74-46e3-80fa-e2528da9910b",
      "name": "3",
      "numberInSession": 3,
      "similarityValue": 0
    },
    {
      "content": "My front door will automatically lock when I leave.",
      "ideaId": "https://innovonto-core.imp.fu-berlin.de/entities/ideas/69730105-93eb-4cad-87cf-cdd895202617",
      "name": "4",
      "numberInSession": 4,
      "similarityValue": 0
    },
    {
      "content": "I can see where people are in my home when I am not there.",
      "ideaId": "https://innovonto-core.imp.fu-berlin.de/entities/ideas/0cb9b87d-aced-4e73-8e9c-e70058dbadd6",
      "name": "5",
      "numberInSession": 5,
      "similarityValue": 0
    },
    {
      "content": "I can see if anyone is walking through the house at night.",
      "ideaId": "https://innovonto-core.imp.fu-berlin.de/entities/ideas/9f1b2d59-e393-4b46-9812-7d12360b55e0",
      "name": "8",
      "numberInSession": 8,
      "similarityValue": 0
    }
  ],
  "content": "ROOT",
  "name": "root",
  "similarityValue": 0
}

**Comment by mackeprm** [comment]
{
  "children": [
    {
      "content": "I think this technology could be used in security settings. For example, in using the way that this software perceives and analyzes movements, we can teach the software to tell us if the human is about to attack someone. There are certain ways a human body moves if they are going to hurt someone physically, by the way they move. If there is a way to tell when someone is moving a certain way, maybe we can prevent an attack. ",
      "ideaId": "https://innovonto-core.imp.fu-berlin.de/entities/ideas/e67499df-cee3-44d2-bde9-c5729ddec8d4",
      "name": "0",
      "numberInSession": 0,
      "similarityValue": 0
    },
    {
      "content": "The way this technology can be used is by detecting the flow of people. For example in a crowded area, if we  can study the way people move, the flow of the crowd and where they go, we can design large areas to be more open. One specific place would be an airport, if we can utilize this technology and learn where people tend to walk, where people tend to gravitate to when going through an airport.  From personal experience I have seen that people tend to 'clog up' a certain area when they go through an airport. If the technology could figure out how we can design a large space, we could better prevent long lines, and too many people crowded in a space.",
      "ideaId": "https://innovonto-core.imp.fu-berlin.de/entities/ideas/207ed8be-e222-441c-bb86-3c75fc918208",
      "name": "1",
      "numberInSession": 1
    }
  ],
  "content": "ROOT",
  "name": "root",
  "similarityValue": 0
}

**Comment by mackeprm** [comment]
{
  "children": [
    {
      "children": [
        {
          "content": "The technology can be used to track migration patterns of invasive organisms, such as algal bloom or certain insects. ",
          "ideaId": "https://innovonto-core.imp.fu-berlin.de/entities/ideas/38c55775-2352-409d-adf4-ecb50123e60a",
          "name": "1",
          "numberInSession": 1,
          "similarityValue": 0
        },
        {
          "content": "The technology can assist with traffic management by analyzing and predicting patterns. ",
          "ideaId": "https://innovonto-core.imp.fu-berlin.de/entities/ideas/12b66ef6-05e2-4020-8933-e6a28e43c8c1",
          "name": "2",
          "numberInSession": 2,
          "similarityValue": 0
        }
      ],
      "content": "The technology can be used to locate people or animals in case of natural disaster. ",
      "ideaId": "https://innovonto-core.imp.fu-berlin.de/entities/ideas/6103638e-b5d2-4414-97e1-687f1c2659ea",
      "name": "0",
      "numberInSession": 0,
      "similarityValue": 0
    },
    {
      "children": [
        {
          "children": [
            {
              "children": [
                {
                  "content": "Measure ocean wave activity in order to provide reports to surfers",
                  "ideaId": "https://innovonto-core.imp.fu-berlin.de/entities/ideas/ffe740c2-ac31-4c6b-8fa7-2ad8b83b27bb",
                  "name": "7",
                  "numberInSession": 7
                }
              ],
              "content": "Measure changes in the size of glaciers",
              "ideaId": "https://innovonto-core.imp.fu-berlin.de/entities/ideas/d920db63-3a6e-4a05-860e-471374361817",
              "name": "5",
              "numberInSession": 5,
              "similarityValue": 0
            },
            {
              "content": "Track a fugitive through any kind of environment or weather",
              "ideaId": "https://innovonto-core.imp.fu-berlin.de/entities/ideas/bcbda5c3-fc3d-42a0-b194-4e088a24cea8",
              "name": "6",
              "numberInSession": 6,
              "similarityValue": 0
            }
          ],
          "content": "Track the size of an oil spill",
          "ideaId": "https://innovonto-core.imp.fu-berlin.de/entities/ideas/ae55e94c-8950-4187-b743-3fd8ca75b07d",
          "name": "4",
          "numberInSession": 4,
          "similarityValue": 0
        }
      ],
      "content": "Estimate crowd sizes at an event. ",
      "ideaId": "https://innovonto-core.imp.fu-berlin.de/entities/ideas/ae61b733-242b-479f-af17-3fb75b2b7dfc",
      "name": "3",
      "numberInSession": 3,
      "similarityValue": 0
    }
  ],
  "content": "ROOT",
  "name": "root",
  "similarityValue": 0
}
