### ISSUE TITLE
Create First Version of Research Page

### ISSUE THREAD

**Issue by mx-e** [FUB-HCC/Innovonto-Core#11]
- [x] implementation based on img

- [x] anything that is unclear functionally can be left for later on

**Comment by mx-e** [comment]
<img width="209" alt="Screenshot 2020-03-08 at 23 37 29" src="https://user-images.githubusercontent.com/13707737/76172409-c87edc80-6195-11ea-930e-f507171086f6.png">

**Comment by mx-e** [comment]
<img width="580" alt="Screenshot 2020-03-08 at 23 38 46" src="https://user-images.githubusercontent.com/13707737/76172422-04b23d00-6196-11ea-913f-ddca39a9651f.png">
<img width="576" alt="Screenshot 2020-03-08 at 23 38 57" src="https://user-images.githubusercontent.com/13707737/76172425-0976f100-6196-11ea-81ff-b4eaf61a5aeb.png">
<img width="579" alt="Screenshot 2020-03-08 at 23 39 02" src="https://user-images.githubusercontent.com/13707737/76172426-0c71e180-6196-11ea-87dc-5b7fed5e8146.png">

**Comment by mackeprm** [comment]
looks good
