### ISSUE TITLE
Create first version of About/Imprint/Privacy Policy Page

### ISSUE THREAD

**Issue by mx-e** [FUB-HCC/Innovonto-Core#21]
- [x] user should see text placeholders for Acknowledgements, Imprint and Privacy Policy

- [x] Scrolling Refs should scroll the page to the appropriate position (link to Privacy Policy -> scroll position at privacy policy)

- [x] styling see img

**Comment by mx-e** [comment]
<img width="1016" alt="Screenshot 2020-03-09 at 12 59 06" src="https://user-images.githubusercontent.com/13707737/76211105-c5233980-6205-11ea-93cd-7676b9b73d49.png">

**Comment by mackeprm** [comment]
is now in master (I'm not sure which pull request this was)
