### ISSUE TITLE
Create first version of Model View

### ISSUE THREAD

**Issue by mx-e** [FUB-HCC/Innovonto-Core#23]
- [x] user should see the autogenerated model view HTML in an iFrame 

- [x] HTML in iFrame should behave like page content on other pages (as much as possible - responsiveness might be tricky) 

- [x] css should be overwritten to match the look and feel of the page (is there additional input for this point ?)

**Comment by mx-e** [comment]
@mackeprm INPUT NEEDED: url where model view is currently hosted (+ maybe some guidance on the styling for css rewrite - more iterative approach otherwise)

**Comment by mackeprm** [comment]
model view is hosted at https://innovonto-core.imp.fu-berlin.de/innovonto/types/
this is created statically by running make in https://github.com/FUB-HCC/Innovonto-Ontology
(this creates a "docs" folder that contains an index-en.html)
and then copied into the nginx
I _think_ the css is this one:
https://github.com/dgarijo/Widoco/blob/master/src/main/resources/lode/bootstrap-yeti.css

But at the moment I'm not sure how to include it in the build pipeline (without having to compile my own widoco)

**Comment by mackeprm** [comment]
innovonto-core/services/entity-server/src/screens/model/ModelOverviewScreen.tsx

**Comment by mackeprm** [comment]
@mx-e do you need more input here?

**Comment by mx-e** [comment]
Well, it turns out this is quite hard to do for security reasons. (Manipulating css of a iframe content that is) 
- Iframe content is rendered as a separate document, so it ignores all css from 'outside'
- manipulating the page after it is loaded is blocked by the browser due to security reasons (you wouldn't want someone to redirect you to facebook login for example, but insert own code to get your credentials for example)

**Comment by mx-e** [comment]
@mackeprm as far as i see it there is two options to proceed: 
1) insert css on the server side
2) manipulate cors headers on the server side to allow this behaviour (see https://stackoverflow.com/questions/25098021/securityerror-blocked-a-frame-with-origin-from-accessing-a-cross-origin-frame)

**Comment by mx-e** [comment]
which one do you want us to explore ?

**Comment by mx-e** [comment]
pushed a version without style changes for now, proceeding with solution map for the moment

**Comment by mackeprm** [comment]
My suggestion would be to insert the css on the server (model) side. I will include a build step in "Innovonto-Ontology" that copies the css after the static html files are generated

**Comment by mx-e** [comment]
.status div{
  display: none;
}

body{
  background-color: white;
}

h1, h2, h3, h4, h5, h6, p, li, span, a {
  font-family: 'Inria Sans', sans-serif;
  font-weight: normal;
}


h2 {
  color: #29893C;
  border-bottom: none !important;
}

h3 {
  margin-top: 35px;
}

h2{
  margin-top: 45px;
}

a{
 color: rgb(56, 178, 54)
}

a:active,a:hover {
  color: rgb(124, 234, 110)
}

**Comment by mx-e** [comment]
try this

**Comment by mx-e** [comment]
for the shields 
<img width="534" alt="Screenshot 2020-03-19 at 15 25 08" src="https://user-images.githubusercontent.com/13707737/77077812-08478e80-69f6-11ea-92b8-1f9a4a46a977.png">

its necessary to change the final word of their url from 'blue' to 'brightgreen' 
<img width="865" alt="Screenshot 2020-03-19 at 15 25 04" src="https://user-images.githubusercontent.com/13707737/77077828-0c73ac00-69f6-11ea-9969-74202a00ffe0.png">

**Comment by mx-e** [comment]
@mackeprm
