### ISSUE TITLE
Integrate Session View

### ISSUE THREAD

**Issue by mx-e** [FUB-HCC/Innovonto-Core#41]
- [x] integrate session view in app (path entities/sessions/:id)
- [x] grey out tree view until available

**Comment by mx-e** [comment]
<img width="966" alt="75073275-65d0e400-54f9-11ea-915f-7476d5380a68" src="https://user-images.githubusercontent.com/13707737/77325304-5de2aa80-6d18-11ea-845f-200e8672c9bd.png">

**Comment by mackeprm** [comment]
TODO Input Data:
Use as example data:
https://innovonto-core.imp.fu-berlin.de/entities/sessions/2ecbb5dd-0d80-4e2b-9a2f-a6feb7c61959

Creator
Start
End
For Timeline View:
hasEvent

**Comment by mackeprm** [comment]
- For the creator link, use the local uuid of the creator field
- For the page title (Bionic Radar: Session) use the following data:
 - For "Bionic Radar": parse local IdeaContestId (lastindexOf("/") in property "hasIdeaContest")
 - For: Session: parse local Session Id (lastIndexOf("/") in property "@id")

**Comment by mackeprm** [comment]
{
  "@id": "https://innovonto-core.imp.fu-berlin.de/entities/sessions/843bad05-15d9-4ed3-9538-511142404863",
  "@type": "inov:BrainstormingSession",
  "creator": "https://innovonto-core.imp.fu-berlin.de/entities/users/97b8506a-8007-4d2c-a380-105233052b5c",
  "hasIdeaContest": "https://innovonto-core.imp.fu-berlin.de/entities/ideaContests/i2m-bionic-radar",
  "hasSubmissionMethod": "https://innovonto-core.imp.fu-berlin.de/entities/submissionMethods/innovonto-mturk-icv-demo",
  "hasChallenge": "https://innovonto-core.imp.fu-berlin.de/entities/challenges/i2m-bionic-radar-abstract",
  "hasTrackingEvent": [
    {
      "id": "https://innovonto-core.imp.fu-berlin.de/entities/trackingEvents/25cea728-7e0b-48c7-b7d3-9d1ab388c268",
      "eventType": "inspiration-response",
      "content": {
        "id": "https://innovonto-core.imp.fu-berlin.de/entities/inspirations/d3569542-674e-4815-b37b-404d24138889",
        "content": "<div class=\"wordcloud-container\"><img src=\"/images/inspirations/walkingHumanInspiration.jpg\"/></div>"
      },
      "timerValue": 1189
    },
    {
      "id": "https://innovonto-core.imp.fu-berlin.de/entities/trackingEvents/a0b7ce72-a58e-4232-8584-5e5b0e7aba82",
      "eventType": "idea-submit",
      "content": {
        "id": "https://innovonto-core.imp.fu-berlin.de/entities/ideas/d471ef67-62a7-4cb0-a652-93ca53d8768c",
        "content": "This would be helpful for our military during war."
      },
      "timerValue": 1085
    },
    {
      "id": "https://innovonto-core.imp.fu-berlin.de/entities/trackingEvents/83b99bcc-7605-4642-a391-19dcc2227141",
      "eventType": "idea-submit",
      "content": {
        "id": "https://innovonto-core.imp.fu-berlin.de/entities/ideas/b746030b-4c9d-4ad0-873e-a8548d30c7de",
        "content": "Hunters could use this to be able to track animals."
      },
      "timerValue": 1021
    },
    {
      "id": "https://innovonto-core.imp.fu-berlin.de/entities/trackingEvents/26444d38-eda1-412e-a098-fa5964fcab9e",
      "eventType": "inspiration-response",
      "content": {
        "id": "https://innovonto-core.imp.fu-berlin.de/entities/inspirations/da884baf-47d1-416d-8275-2e3f96077408",
        "content": "<div class=\"wordcloud-container\"><img src=\"/images/inspirations/Technologie_Wordcloud_2_3.jpg\"/></div>"
      },
      "timerValue": 982
    },
    {
      "id": "https://innovonto-core.imp.fu-berlin.de/entities/trackingEvents/219571d1-cc85-46b7-ba5d-d96381d34419",
      "eventType": "inspiration-response",
      "content": {
        "id": "https://innovonto-core.imp.fu-berlin.de/entities/inspirations/da884baf-47d1-416d-8275-2e3f96077408",
        "content": "<div class=\"wordcloud-container\"><img src=\"/images/inspirations/Technologie_Wordcloud_2_3.jpg\"/></div>"
      },
      "timerValue": 977
    },
    {
      "id": "https://innovonto-core.imp.fu-berlin.de/entities/trackingEvents/cf41d8a9-242f-4e4d-88f2-2670728a7973",
      "eventType": "inspiration-response",
      "content": {
        "id": "https://innovonto-core.imp.fu-berlin.de/entities/inspirations/d3569542-674e-4815-b37b-404d24138889",
        "content": "<div class=\"wordcloud-container\"><img src=\"/images/inspirations/walkingHumanInspiration.jpg\"/></div>"
      },
      "timerValue": 976
    },
    {
      "id": "https://innovonto-core.imp.fu-berlin.de/entities/trackingEvents/215202b6-8fc5-4ae4-ad25-7bf1d0446cce",
      "eventType": "inspiration-response",
      "content": {
        "id": "https://innovonto-core.imp.fu-berlin.de/entities/inspirations/da884baf-47d1-416d-8275-2e3f96077408",
        "content": "<div class=\"wordcloud-container\"><img src=\"/images/inspirations/Technologie_Wordcloud_2_3.jpg\"/></div>"
      },
      "timerValue": 974
    },
    {
      "id": "https://innovonto-core.imp.fu-berlin.de/entities/trackingEvents/2cb8c313-9db5-492a-bfee-9a31ad34ed4d",
      "eventType": "idea-submit",
      "content": {
        "id": "https://innovonto-core.imp.fu-berlin.de/entities/ideas/b3d82b61-6299-4b90-bf8c-c54d01a9093a",
        "content": "This could be implemented in security alarms."
      },
      "timerValue": 893
    },
    {
      "id": "https://innovonto-core.imp.fu-berlin.de/entities/trackingEvents/1bf060e2-6a27-419c-bdbe-143fc70dafad",
      "eventType": "idea-submit",
      "content": {
        "id": "https://innovonto-core.imp.fu-berlin.de/entities/ideas/40fd4639-6cfb-4491-867f-5ad3493cebf3",
        "content": "Police could use this technology to be able to better help find criminals at night."
      },
      "timerValue": 820
    },
    {
      "id": "https://innovonto-core.imp.fu-berlin.de/entities/trackingEvents/50a8b60b-29e8-4893-b892-cfaa2b583650",
      "eventType": "idea-submit",
      "content": {
        "id": "https://innovonto-core.imp.fu-berlin.de/entities/ideas/8d7570d0-4265-47a6-9f3e-fce82430452d",
        "content": "This could be helpful for certain parts of the world that we need to account for population for a certain species."
      },
      "timerValue": 451
    },
    {
      "id": "https://innovonto-core.imp.fu-berlin.de/entities/trackingEvents/38713eb9-06a2-4d8e-ac42-adcbbf5d7903",
      "eventType": "inspiration-response",
      "content": {
        "id": "https://innovonto-core.imp.fu-berlin.de/entities/inspirations/da884baf-47d1-416d-8275-2e3f96077408",
        "content": "<div class=\"wordcloud-container\"><img src=\"/images/inspirations/Technologie_Wordcloud_2_3.jpg\"/></div>"
      },
      "timerValue": 401
    }
  ]
}

**Comment by mackeprm** [comment]
{
  "@context": {
    "title": {
      "@id": "http://purl.org/dc/terms/title"
    },
    "description": {
      "@id": "http://purl.org/dc/terms/description"
    },
    "ratingValue": {
      "@id": "http://purl.org/gi2mo/ns#ratingValue",
      "@type": "http://www.w3.org/2001/XMLSchema#integer"
    },
    "minRatingValue": {
      "@id": "http://purl.org/gi2mo/ns#minRatingValue",
      "@type": "http://www.w3.org/2001/XMLSchema#integer"
    },
    "maxRatingValue": {
      "@id": "http://purl.org/gi2mo/ns#maxRatingValue",
      "@type": "http://www.w3.org/2001/XMLSchema#integer"
    },
    "creator": {
      "@id": "http://purl.org/dc/terms/creator",
      "@type": "@id"
    },
    "timerValue": {
      "@id": "http://purl.org/innovonto/types/#timerValue",
      "@type": "http://www.w3.org/2001/XMLSchema#integer"
    },
    "serverTimestamp": {
      "@id": "http://purl.org/innovonto/types/#serverTimestamp"
    },
    "eventType": {
      "@id": "http://purl.org/innovonto/types/#eventType"
    },
    "hasIdeaContest": {
      "@id": "http://purl.org/gi2mo/ns#hasIdeaContest",
      "@type": "@id"
    },
    "timeSinceLastIdea": {
      "@id": "http://purl.org/innovonto/types/#timeSinceLastIdea"
    },
    "formattedTimeSinceLastIdea": {
      "@id": "http://purl.org/innovonto/types/#formattedTimeSinceLastIdea"
    },
    "content": {
      "@id": "http://purl.org/gi2mo/ns#content"
    },
    "created": {
      "@id": "http://purl.org/dc/terms/created"
    },
    "status": {
      "@id": "http://purl.org/innovonto/legacy/types#status",
      "@type": "@id"
    },
    "ideaType": {
      "@id": "http://purl.org/innovonto/types/#ideaType"
    },
    "hasAnnotation": {
      "@id": "http://purl.org/innovonto/types/#hasAnnotation",
      "@type": "@id"
    },
    "hasBrainstormingSession": {
      "@id": "http://purl.org/innovonto/types/#hasBrainstormingSession",
      "@type": "@id"
    },
    "numberInSession": {
      "@id": "http://purl.org/innovonto/types/#numberInSession"
    },
    "hasChallenge": {
      "@id": "http://purl.org/innovonto/types/#hasChallenge",
      "@type": "@id"
    },
    "hasSubmissionMethod": {
      "@id": "http://purl.org/gi2mo/ns#hasSubmissionMethod",
      "@type": "@id"
    },
    "submittedIdea": {
      "@id": "http://purl.org/innovonto/types/#submittedIdea",
      "@type": "@id"
    },
    "hasInspiration": {
      "@id": "http://purl.org/innovonto/types/#hasInspiration",
      "@type": "@id"
    },
    "hasReview": {
      "@id": "http://purl.org/gi2mo/ns#hasReview",
      "@type": "@id"
    },
    "hasTrackingEvent": {
      "@id": "http://purl.org/innovonto/types/#hasTrackingEvent",
      "@type": "@id"
    },
    "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "dcterms": "http://purl.org/dc/terms/",
    "gi2mo": "http://purl.org/gi2mo/ns#",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
    "oid": "http://purl.org/innovonto/legacy/types#",
    "inov": "http://purl.org/innovonto/types/#"
  },
  "@id": "https://innovonto-core.imp.fu-berlin.de/entities/sessions/2ecbb5dd-0d80-4e2b-9a2f-a6feb7c61959",
  "@type": "inov:BrainstormingSession",
  "creator": "https://innovonto-core.imp.fu-berlin.de/entities/users/4a54925d-12b6-4790-aa8b-0b676bb48f7a",
  "hasIdeaContest": "https://innovonto-core.imp.fu-berlin.de/entities/ideaContests/i2m-bionic-radar",
  "hasSubmissionMethod": "https://innovonto-core.imp.fu-berlin.de/entities/submissionMethods/innovonto-mturk-icv-demo",
  "hasChallenge": "https://innovonto-core.imp.fu-berlin.de/entities/challenges/i2m-bionic-radar-technical",
  "hasTrackingEvent": [
    {
      "id": "https://innovonto-core.imp.fu-berlin.de/entities/trackingEvents/4413e301-0ed4-4572-b306-d5ea8347d558",
      "eventType": "idea-submit",
      "content": {
        "id": "https://innovonto-core.imp.fu-berlin.de/entities/ideas/cf65b021-620f-43fe-9473-1712be788cde",
        "content": "This can enable me to interact and see where others are in my home."
      },
      "timerValue": 1065
    },
    {
      "id": "https://innovonto-core.imp.fu-berlin.de/entities/trackingEvents/14074b8b-d0fc-4be7-9d4d-e20174eb4ef2",
      "eventType": "idea-submit",
      "content": {
        "id": "https://innovonto-core.imp.fu-berlin.de/entities/ideas/efd50c16-af7e-48fa-825b-ff512e54817b",
        "content": "I will know where my pet is in the home."
      },
      "timerValue": 1008
    },
    {
      "id": "https://innovonto-core.imp.fu-berlin.de/entities/trackingEvents/e6154884-d149-40aa-9a4a-bfb664912f87",
      "eventType": "idea-submit",
      "content": {
        "id": "https://innovonto-core.imp.fu-berlin.de/entities/ideas/c22eddef-a9f2-4e0d-8bc7-766ce2912120",
        "content": "I will know if someone enters my home."
      },
      "timerValue": 967
    },
    {
      "id": "https://innovonto-core.imp.fu-berlin.de/entities/trackingEvents/b17f6078-921d-42d5-adec-ffde65fa5f77",
      "eventType": "idea-submit",
      "content": {
        "id": "https://innovonto-core.imp.fu-berlin.de/entities/ideas/9198ac8e-ef74-46e3-80fa-e2528da9910b",
        "content": "I can have lights automatically turn on when I enter a room."
      },
      "timerValue": 873
    },
    {
      "id": "https://innovonto-core.imp.fu-berlin.de/entities/trackingEvents/c27c19db-ca36-4bf8-87f4-c62711760806",
      "eventType": "inspiration-response",
      "content": {
        "id": "https://innovonto-core.imp.fu-berlin.de/entities/inspirations/d3569542-674e-4815-b37b-404d24138889",
        "content": "<div class=\"wordcloud-container\"><img src=\"/images/inspirations/walkingHumanInspiration.jpg\"/></div>"
      },
      "timerValue": 827
    },
    {
      "id": "https://innovonto-core.imp.fu-berlin.de/entities/trackingEvents/01eb2e99-eab7-4350-a406-a0c5a05c60c6",
      "eventType": "idea-submit",
      "content": {
        "id": "https://innovonto-core.imp.fu-berlin.de/entities/ideas/69730105-93eb-4cad-87cf-cdd895202617",
        "content": "My front door will automatically lock when I leave."
      },
      "timerValue": 653
    },
    {
      "id": "https://innovonto-core.imp.fu-berlin.de/entities/trackingEvents/5ec7034d-4606-468b-ae53-61e2d5e4e4d7",
      "eventType": "idea-submit",
      "content": {
        "id": "https://innovonto-core.imp.fu-berlin.de/entities/ideas/0cb9b87d-aced-4e73-8e9c-e70058dbadd6",
        "content": "I can see where people are in my home when I am not there."
      },
      "timerValue": 600
    },
    {
      "id": "https://innovonto-core.imp.fu-berlin.de/entities/trackingEvents/10ca59bf-cb3c-4e1d-8a8e-3df7d76ea15a",
      "eventType": "idea-submit",
      "content": {
        "id": "https://innovonto-core.imp.fu-berlin.de/entities/ideas/779c37ed-e6c4-44ca-bcbf-6b4d807627ef",
        "content": "I will see where an intruder is in my home at night."
      },
      "timerValue": 463
    },
    {
      "id": "https://innovonto-core.imp.fu-berlin.de/entities/trackingEvents/5e1e820d-c229-4dfa-b738-5e8d57181fab",
      "eventType": "idea-submit",
      "content": {
        "id": "https://innovonto-core.imp.fu-berlin.de/entities/ideas/8c768672-f341-47e4-9e5e-696bca0049b3",
        "content": "I will know which family member is entering the home."
      },
      "timerValue": 337
    },
    {
      "id": "https://innovonto-core.imp.fu-berlin.de/entities/trackingEvents/dd550224-01a3-486f-a042-bea99ec82bb0",
      "eventType": "idea-submit",
      "content": {
        "id": "https://innovonto-core.imp.fu-berlin.de/entities/ideas/9f1b2d59-e393-4b46-9812-7d12360b55e0",
        "content": "I can see if anyone is walking through the house at night."
      },
      "timerValue": 256
    },
    {
      "id": "https://innovonto-core.imp.fu-berlin.de/entities/trackingEvents/df195d05-9f3e-40be-b364-eb8882b0b697",
      "eventType": "idea-submit",
      "content": {
        "id": "https://innovonto-core.imp.fu-berlin.de/entities/ideas/c82bf1d4-dbca-4524-a722-c425ad959aa7",
        "content": "I will know if a stranger is in my home."
      },
      "timerValue": 203
    },
    {
      "id": "https://innovonto-core.imp.fu-berlin.de/entities/trackingEvents/a22761fe-b77d-477c-b03d-4684f153db72",
      "eventType": "inspiration-response",
      "content": {
        "id": "https://innovonto-core.imp.fu-berlin.de/entities/inspirations/d3569542-674e-4815-b37b-404d24138889",
        "content": "<div class=\"wordcloud-container\"><img src=\"/images/inspirations/walkingHumanInspiration.jpg\"/></div>"
      },
      "timerValue": 167
    },
    {
      "id": "https://innovonto-core.imp.fu-berlin.de/entities/trackingEvents/eb6a9e83-2657-43e7-a061-dfe9647a9758",
      "eventType": "idea-submit",
      "content": {
        "id": "https://innovonto-core.imp.fu-berlin.de/entities/ideas/726540a9-0775-48bb-bf8c-a9a7e196a5bd",
        "content": "I would see when someone is moving in my home."
      },
      "timerValue": 79
    }
  ]
}
