### ISSUE TITLE
Create First Version of Landing Page

### ISSUE THREAD

**Issue by mx-e** [FUB-HCC/Innovonto-Core#5]
- [x] Landing Page should contain Header Jumbotron with background and three info boxes (see image)

- [x] Three paragraphs of static text which should be easily replaceable 

- [x] Content is centred in the middle part and should not scale beyond a certain width

**Comment by mx-e** [comment]
<img width="506" alt="Screenshot 2020-03-08 at 17 58 01" src="https://user-images.githubusercontent.com/13707737/76167364-5c38b480-6166-11ea-9a67-699b1f31c1fe.png">

**Comment by mackeprm** [comment]
Looks good
