### ISSUE TITLE
Create IdeaContestDetailView

### ISSUE THREAD

**Issue by mackeprm** [FUB-HCC/Innovonto-Core#56]
Under
https://innovonto-core.imp.fu-berlin.de/entities/ideaContests/i2m-TCO

we are currently showing the fallback view. We could integrate a styled version of an idea contest detail view and then link it in the project overview

**Comment by mx-e** [comment]
INPUT needed: how does one get the data ? How should the component look ?

**Comment by mackeprm** [comment]
The component should look similar to the other "*Details Component"
The component should feature the following content:

- title (if present), otherwise local id
- description
- startDate / endDate
- research-descriptions (if present):
  - title or local id
  - description

The component should include the following links:
- Idea-Map for the project

**Comment by mackeprm** [comment]
Master now contains a stub for IdeaContest that already requests the data. Current testvalues for ideacontest-deatils are:
http://localhost:3000/entities/ideaContests/i2m-TCO
http://localhost:3000/entities/ideaContests/i2m-bionic-radar
