### ISSUE TITLE
Create First Version of Idea Details Component

### ISSUE THREAD

**Issue by mx-e** [FUB-HCC/Innovonto-Core#8]
- [x]  idea details UI as seen in img

- [x] info, network, social, history tabs

- [x] only info tab needs to work for now

**Comment by mx-e** [comment]
<img width="973" alt="Screenshot 2020-03-08 at 18 22 18" src="https://user-images.githubusercontent.com/13707737/76167802-c69f2400-6169-11ea-9803-0cc7a7da02d0.png">

**Comment by mx-e** [comment]
@mackeprm INPUT NEEDED: dummy request json (maybe several for testing)

**Comment by mackeprm** [comment]
WIP: AC1 Examples (not processed yet)

GROUP PHASE Example:
<https://innovonto-core.imp.fu-berlin.de/entities/ideas/d7395f48-d0c3-4c60-aa3f-91c0777f2c30>

COMPLETE Example:
<https://innovonto-core.imp.fu-berlin.de/entities/ideas/55ea193b-16f8-408d-b4c9-f820679c2aab>

SELECTED_BY_MODERATORS Example:
<https://innovonto-core.imp.fu-berlin.de/entities/ideas/80257178-6d76-430e-8f3b-133137768d0f>

**Comment by mackeprm** [comment]
Use typescript component as input for first iteration:
services/entity-server/src/components/entities/ideas/IdeaDetails.tsx

**Comment by mackeprm** [comment]
First Version:
Info: As typescript
Network:
 - Neighbourhood: nicht (ausgegraut)
 - Session view: statisches bild + link auf /entities/sessions/X wenn vorhanden
 - InspiredBy: Aus JSON Daten rausnehmen und als links anzeigen

Social: Nicht (ausgegraut)
History: Nicht (ausgegraut)

**Comment by mx-e** [comment]
@mackeprm the urls up there don't really work anymore since you hosted the current app :D 
I'll start writing it with static dat for now, but i need this as input

**Comment by mackeprm** [comment]
ah dammit
I will postjson responses for the ideas here

**Comment by mackeprm** [comment]
{
	"@id": "https://innovonto-core.imp.fu-berlin.de/entities/ideas/d7395f48-d0c3-4c60-aa3f-91c0777f2c30",
	"@type": "gi2mo:Idea",
	"created": "2018-06-20T18:00Z",
	"creator": "https://innovonto-core.imp.fu-berlin.de/entities/users/b2214b43-dc2a-4057-8854-fbf2a725d49c",
	"content": "This tag could be attached to doorhandles, water faucets, toilet seats and other objects in public toilettes to control and remind the cleaning personal to disinfect in a appropriate interval.\n\n                    could be attached to existing facilities…",
	"hasIdeaContest": "https://innovonto-core.imp.fu-berlin.de/entities/ideaContests/i2m-TCO",
	"hasSubmissionMethod": "https://innovonto-core.imp.fu-berlin.de/entities/submissionMethods/TCO-Group-Phase",
	"enhancedInGroupPhase": "true",
	"status": "http://purl.org/innovonto/i2m-legacy/status/GROUP_PHASE_IDEA",
	"hasChallenge": "https://innovonto-core.imp.fu-berlin.de/entities/challenges/i2m-TCO",
	"hasTextualRefinement": [{
			"@type": "inov:TextualRefinement",
			"description": "What's new in your idea?",
			"contentGerman": {
				"@language": "de",
				"@value": "Schnelle Sichtbarkeit von Reinigungsbedarf, ermöglicht Reinigen nach Bedarf (und damit Zeitersparnis)"
			}
		},
		{
			"@type": "inov:TextualRefinement",
			"description": "What are the strengths of your idea?",
			"contentGerman": {
				"@language": "de",
				"@value": "Direkter Nutzen für Patienten / Kunden aber auch Unternehmen (Positionierung)"
			}
		},
		{
			"@type": "inov:TextualRefinement",
			"description": "How is the problem you are solving solved?",
			"contentGerman": {
				"@language": "de",
				"@value": "TCO Beschichtung als direkt–Feedback "
			}
		}
	],
	"inspiredBy": ["https://innovonto-core.imp.fu-berlin.de/entities/ideas/810bda91-8068-48ee-83e3-ef2b6a54a01e"],
	"seeAlso": "http://purl.org/innovonto/i2m-legacy/168-4"
}

**Comment by mackeprm** [comment]
Another TCO example:
{
	"@id": "https://innovonto-core.imp.fu-berlin.de/entities/ideas/80257178-6d76-430e-8f3b-133137768d0f",
	"@type": "gi2mo:Idea",
	"created": "2018-05-31T12:15Z",
	"title": "smart tag",
	"content": "helps you to mark, rate and finde important documents in you analog folder.\r\n            this technology combines documents and certificates made of paper with digital advantages.",
	"hasCategory": [
		"http://purl.org/innovonto/i2m-legacy/category/School",
		"http://purl.org/innovonto/i2m-legacy/category/Professionals",
		"http://purl.org/innovonto/i2m-legacy/category/Kindergarten",
		"http://purl.org/innovonto/i2m-legacy/category/Men",
		"http://purl.org/innovonto/i2m-legacy/category/Public+authorities",
		"http://purl.org/innovonto/i2m-legacy/category/Offices",
		"http://purl.org/innovonto/i2m-legacy/category/Pupils",
		"http://purl.org/innovonto/i2m-legacy/category/Employees",
		"http://purl.org/innovonto/i2m-legacy/category/University",
		"http://purl.org/innovonto/i2m-legacy/category/Museums",
		"http://purl.org/innovonto/i2m-legacy/category/Retirement+home",
		"http://purl.org/innovonto/i2m-legacy/category/Women",
		"http://purl.org/innovonto/i2m-legacy/category/Students",
		"http://purl.org/innovonto/i2m-legacy/category/Library"
	],
	"hasContributor": "https://innovonto-core.imp.fu-berlin.de/entities/users/05a374e2-4061-490a-977a-ba289dbecb94",
	"hasCreator": "https://innovonto-core.imp.fu-berlin.de/entities/users/43f7c9ff-f990-4a18-b3ff-b4404fad8a49",
	"hasIdeaContest": "https://innovonto-core.imp.fu-berlin.de/entities/ideaContests/i2m-TCO",
	"hasSubmissionMethod": "https://innovonto-core.imp.fu-berlin.de/entities/submissionMethods/OntoideaLegacyAppTCO",
	"createdInternally": "true",
	"filteredInGroupPhase": "true",
	"preselectedFor": "https://innovonto-core.imp.fu-berlin.de/entities/users/05a374e2-4061-490a-977a-ba289dbecb94",
	"status": "http://purl.org/innovonto/i2m-legacy/status/SELECTED_BY_MODERATORS",
	"assignedTo": "https://innovonto-core.imp.fu-berlin.de/entities/users/05a374e2-4061-490a-977a-ba289dbecb94",
	"hasAnnotation": [
		"https://innovonto-core.imp.fu-berlin.de/entities/annotationCandidates/4651",
		"https://innovonto-core.imp.fu-berlin.de/entities/annotationCandidates/4654",
		"https://innovonto-core.imp.fu-berlin.de/entities/annotationCandidates/4650",
		"https://innovonto-core.imp.fu-berlin.de/entities/annotationCandidates/4649",
		"https://innovonto-core.imp.fu-berlin.de/entities/annotationCandidates/4652",
		"https://innovonto-core.imp.fu-berlin.de/entities/annotationCandidates/4653"
	],
	"hasChallenge": "https://innovonto-core.imp.fu-berlin.de/entities/challenges/i2m-TCO",
	"hasTextualRefinement": [{
			"description": "Describe your idea in more detail (e.g., how is it used?)",
			"content": "could be used in offices and authorities aswell.\r\n                the tag could be used to identify modify documents and passports to make them forgery-proof…\r\n            "
		},
		{
			"description": "Which problem does the idea solve?",
			"content": "labeling, marking and forgery-proofing…\r\n            "
		}
	],
	"icon": "/media/tco/icons/169.png",
	"inspiredBy": "https://innovonto-core.imp.fu-berlin.de/entities/ideas/a9881362-fad6-4882-b234-83567e2192c7",
	"seeAlso": "http://purl.org/innovonto/i2m-legacy/169"
}

**Comment by mackeprm** [comment]
Bionic Radar Spark Example:
{
	"@id": "https://innovonto-core.imp.fu-berlin.de/entities/ideas/cf65b021-620f-43fe-9473-1712be788cde",
	"@type": "gi2mo:Idea",
	"created": "2019-05-02T15:37:25.212Z",
	"creator": "https://innovonto-core.imp.fu-berlin.de/entities/users/4a54925d-12b6-4790-aa8b-0b676bb48f7a",
	"content": "This can enable me to interact and see where others are in my home.",
	"hasIdeaContest": "https://innovonto-core.imp.fu-berlin.de/entities/ideaContests/i2m-bionic-radar",
	"hasSubmissionMethod": "https://innovonto-core.imp.fu-berlin.de/entities/submissionMethods/innovonto-mturk-icv-demo",
	"status": "http://purl.org/innovonto/i2m-legacy/status/spark-approved",
	"hasAnnotation": [
		"https://innovonto-core.imp.fu-berlin.de/entities/annotationCandidates/ca4eaaf6-29fc-47cc-8497-2e1d7c969186",
		"https://innovonto-core.imp.fu-berlin.de/entities/annotationCandidates/0f4855f5-8853-404e-a900-2919b6e760da"
	],
	"hasChallenge": "https://innovonto-core.imp.fu-berlin.de/entities/challenges/i2m-bionic-radar-technical",
	"numberInSession": "0"
}

**Comment by mackeprm** [comment]
TODO: The Bionic Radar Ideas are missing their session information :/

**Comment by mx-e** [comment]
@mackeprm komme gut voran: 
- kannst du mir noch mal Bilder von der Network Page +  den 3 Previews schicken, meine Sketch Probelizenz ist ausgelaufen. 
- inspireBy ist klar, welches Attribut bezieht sich auf die Session ?

**Comment by mackeprm** [comment]
Das Session Attribut ist: 
"hasBrainstormingSession: "https://innovonto-core.imp.fu-berlin.de/entities/sessions/2ecbb5dd-0d80-4e2b-9a2f-a6feb7c61959",
(siehe letztes beispiel)

**Comment by mackeprm** [comment]
![Idea Details - Network](https://user-images.githubusercontent.com/10158210/77224325-bd985480-6b64-11ea-89b4-e84b35633ef1.png)

**Comment by mackeprm** [comment]
![Group 12](https://user-images.githubusercontent.com/10158210/77224329-c8eb8000-6b64-11ea-894a-2e28c29f1d49.png)
![Group 13](https://user-images.githubusercontent.com/10158210/77224330-c9841680-6b64-11ea-9835-82303a91a450.png)

**Comment by mackeprm** [comment]
looks good!
