### ISSUE TITLE
Create first version of User Detail Component

### ISSUE THREAD

**Issue by mx-e** [FUB-HCC/Innovonto-Core#9]

**Comment by mx-e** [comment]
<img width="498" alt="Screenshot 2020-03-08 at 18 30 57" src="https://user-images.githubusercontent.com/13707737/76167961-f7338d80-616a-11ea-8961-aaa04a090069.png">

**Comment by mx-e** [comment]
@mackeprm INPUT NEEDED: dummy request json (+ whats behind Ideas and Surveys ? )

**Comment by mackeprm** [comment]
"@id": "https://innovonto-core.imp.fu-berlin.de/entities/users/583fe434-db34-4e7c-9735-56c116e66f9c",
  "@type": "inov:Ideator",
  "role": "ROLE_EXPLORER",
  "age": "24",
  "gender": "female",
  "hasSubmittedIdeasForChallenge": ["https://innovonto-core.imp.fu-berlin.de/entities/challenges/i2m-TCO"],
  "hasSubmittedIdeasForIdeaContest": ["https://innovonto-core.imp.fu-berlin.de/entities/ideaContests/i2m-TCO"],
  "highestDegree": "Master/Diploma",
  "isCreatorOf": [
    "https://innovonto-core.imp.fu-berlin.de/entities/ideas/9eee943f-b704-43e7-abc7-95aa189262a3",
    "https://innovonto-core.imp.fu-berlin.de/entities/ideas/0acdd7fb-57dd-4ecd-bc8f-49912ee716ec"
  ],
  "nationality": "German",
  "occupation": "Student but also Assistant for Marketing and Communication for IP-Commercialisation ",
  "occupationalGroup": "Industry"
}

**Comment by mackeprm** [comment]
`{
	"@id": "https://innovonto-core.imp.fu-berlin.de/entities/users/015b6209-e9d6-4039-99b3-73825c50284a",
	"@type": "inov:Ideator",
	"age": "25",
	"gender": "Male",
	"hasBrainstormingSession": "https://innovonto-core.imp.fu-berlin.de/entities/sessions/d0197b4a-6edc-4d65-940a-9320c6ba70f9",
	"hasSubmittedIdeasForChallenge": "https://innovonto-core.imp.fu-berlin.de/entities/challenges/i2m-bionic-radar-test-metaphorical",
	"hasSubmittedIdeasForIdeaContest": "https://innovonto-core.imp.fu-berlin.de/entities/ideaContests/i2m-bionic-radar",
	"highestDegree": "Bachelor",
	"isCreatorOf": ["https://innovonto-core.imp.fu-berlin.de/entities/ideas/302743e0-aa6e-4483-be7a-3735369c7679", "https://innovonto-core.imp.fu-berlin.de/entities/ideas/5d9acac4-3ff0-4e41-90ed-cacbbfec4f13", "https://innovonto-core.imp.fu-berlin.de/entities/ideas/a4e43b6f-49a8-4967-9d3d-b397690213d4", "https://innovonto-core.imp.fu-berlin.de/entities/ideas/1fa29d07-b82d-4cb9-b50d-5e8723a1112e", "https://innovonto-core.imp.fu-berlin.de/entities/ideas/76958807-2c09-428c-95fe-c75bb6d7e931", "https://innovonto-core.imp.fu-berlin.de/entities/ideas/ea233a4b-8d10-42d2-827a-42b1026abec9", "https://innovonto-core.imp.fu-berlin.de/entities/ideas/288e3f26-cc82-461d-adbf-dcdb5a7e31a0", "https://innovonto-core.imp.fu-berlin.de/entities/ideas/4302c05e-323c-4e02-b7d1-95765cf3f3ea", "https://innovonto-core.imp.fu-berlin.de/entities/ideas/6a1b8dc2-38cc-4a4a-aaa9-b435fb1279ff", "https://innovonto-core.imp.fu-berlin.de/entities/ideas/8e9ae32e-1d44-4a8e-bdc1-aabd8a011c85", "https://innovonto-core.imp.fu-berlin.de/entities/ideas/c7a4e622-7f6c-4748-9307-9341b5197372", "https://innovonto-core.imp.fu-berlin.de/entities/ideas/bd97a74d-0d03-4b4a-9db0-84b0ed79ae47", "https://innovonto-core.imp.fu-berlin.de/entities/ideas/ff7847a4-7355-4fd5-85b4-3a9232e6e360", "https://innovonto-core.imp.fu-berlin.de/entities/ideas/5d35439f-4808-4dd2-94f6-0820c086cfdb", "https://innovonto-core.imp.fu-berlin.de/entities/ideas/cb00cde4-5c3e-412f-a55a-7f7a8b05b264"],
	"nationality": "American",
	"occupation": "Unemployed/Full time MTurk"
}`

**Comment by mackeprm** [comment]
{
	"@id": "https://innovonto-core.imp.fu-berlin.de/entities/users/04f84d28-e1d0-4603-b4d5-06f429497533",
	"@type": "inov:Ideator",
	"age": "30",
	"gender": "Male",
	"hasBrainstormingSession": "https://innovonto-core.imp.fu-berlin.de/entities/sessions/9e73400e-b690-4936-ad14-b1d144a33a13",
	"hasSubmittedIdeasForChallenge": "https://innovonto-core.imp.fu-berlin.de/entities/challenges/i2m-bionic-radar-abstract",
	"hasSubmittedIdeasForIdeaContest": "https://innovonto-core.imp.fu-berlin.de/entities/ideaContests/i2m-bionic-radar",
	"highestDegree": "Bachelor",
	"isCreatorOf": ["https://innovonto-core.imp.fu-berlin.de/entities/ideas/41b9e50b-924b-48ab-b370-d3bfdd0d513d", "https://innovonto-core.imp.fu-berlin.de/entities/ideas/80d9839f-9fd6-4807-8a21-4035aac48e33", "https://innovonto-core.imp.fu-berlin.de/entities/ideas/64ca3aa0-4237-4d46-a92e-2807f00291a8", "https://innovonto-core.imp.fu-berlin.de/entities/ideas/ce08ee96-4422-4afe-8afc-5551c6647187", "https://innovonto-core.imp.fu-berlin.de/entities/ideas/9660eb93-cef2-4cfd-82d8-52077c0d9a20", "https://innovonto-core.imp.fu-berlin.de/entities/ideas/85e6db6d-447b-48ba-aebe-f81a9e69a232", "https://innovonto-core.imp.fu-berlin.de/entities/ideas/5bf182e9-0160-4c67-b3f6-6775d64ff732", "https://innovonto-core.imp.fu-berlin.de/entities/ideas/c0874944-3587-4961-b060-e982862fe832", "https://innovonto-core.imp.fu-berlin.de/entities/ideas/2a06c579-c172-4f4c-bb9b-7c087ea6fd07"],
	"nationality": "US",
	"occupation": "Analyst"
}
